### ISSUE TITLE
Implement game ticks

### ISSUE THREAD

**Issue by thimovss** [Sewerbird/Helios2400#29]
Write the main update function to calculate how many game ticks have gone by since last call.
A game tick being a time of either 0.1 or 0.2 seconds.
This should increase the overall performance of the game.

**Comment by Sewerbird** [comment]
@thimovss  I've introduced the update throttle. However, it does not seem to meaningfully impact the current FPS performance of the game: the draw() call is simply very heavy right now.

Closing this issue since we can do an optimization run after the Engine MVP milestone is reached, and this particular issue is addressed.
